name: sdl2
description: A Dart library for accessing common SDL 2.26.3 (stable) APIs using, FFI.
version: 1.4.2
homepage: https://github.com/sansuido/sdl2
repository: https://github.com/sansuido/sdl2

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  ffi: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  change_case: ^1.0.2
