name: sdl2
description: A Dart library for accessing common SDL 2.0.22(stable) APIs using, FFI.
version: 1.1.1
homepage: https://github.com/sansuido/sdl2
repository: https://github.com/sansuido/sdl2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ffi: ^2.0.0
