name: sdl2
description: A Dart library for accessing common SDL 2.28.2 (stable) APIs using, FFI.
version: 1.5.3
homepage: https://github.com/sansuido/sdl2
repository: https://github.com/sansuido/sdl2

environment:
  sdk: '>=3.0.7 <4.0.0'

dependencies:
  ffi: ^2.0.2

dev_dependencies:
  lints: ^2.1.1
  change_case: ^1.1.0
