name: sdl2
description: A Dart library for accessing common SDL2 APIs using, FFI.
version: 1.0.10
homepage: https://github.com/sansuido/sdl2
repository: https://github.com/sansuido/sdl2

environment:
  sdk: '>=2.13.4 <3.0.0'

dependencies:
  ffi: ^1.1.2
