name: sdl2
description: SDL2 for Dart
version: 1.0.6
homepage: https://github.com/sansuido/sdl2
repository: https://github.com/sansuido/sdl2

environment:
  sdk: '>=2.13.1 <3.0.0'

dependencies:
  ffi: ^1.1.0

